// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASQnFt8LKQFg1p6z9xGs2uH1tXekddhWM',
    appId: '1:782658379168:web:abc3506cdf53d30a7ad8c5',
    messagingSenderId: '782658379168',
    projectId: 'eventmanagementapp-d8bc9',
    authDomain: 'eventmanagementapp-d8bc9.firebaseapp.com',
    storageBucket: 'eventmanagementapp-d8bc9.firebasestorage.app',
    measurementId: 'G-6K3LJDTS9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGVqthwjv9jti4lzmvronbworkLPQohlI',
    appId: '1:782658379168:android:cb36dab5ec4eeb667ad8c5',
    messagingSenderId: '782658379168',
    projectId: 'eventmanagementapp-d8bc9',
    storageBucket: 'eventmanagementapp-d8bc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcfpCv9PGpSFIUeEbmiqAX5y_lRb_BTCw',
    appId: '1:782658379168:ios:738ddaa55e5259247ad8c5',
    messagingSenderId: '782658379168',
    projectId: 'eventmanagementapp-d8bc9',
    storageBucket: 'eventmanagementapp-d8bc9.firebasestorage.app',
    iosBundleId: 'com.example.cse23523',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcfpCv9PGpSFIUeEbmiqAX5y_lRb_BTCw',
    appId: '1:782658379168:ios:738ddaa55e5259247ad8c5',
    messagingSenderId: '782658379168',
    projectId: 'eventmanagementapp-d8bc9',
    storageBucket: 'eventmanagementapp-d8bc9.firebasestorage.app',
    iosBundleId: 'com.example.cse23523',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASQnFt8LKQFg1p6z9xGs2uH1tXekddhWM',
    appId: '1:782658379168:web:b758ed8bc129fb0b7ad8c5',
    messagingSenderId: '782658379168',
    projectId: 'eventmanagementapp-d8bc9',
    authDomain: 'eventmanagementapp-d8bc9.firebaseapp.com',
    storageBucket: 'eventmanagementapp-d8bc9.firebasestorage.app',
    measurementId: 'G-H93T23R4C5',
  );

}